const products = [
  {
    id: "rec43w3ipXvP28vog",
    title: "high-back bench",
    company: "ikea",
    image: "https://course-api.com/images/store/product-1.jpeg",
    price: 20000,
  },
  {
    id: "rec4f2RIftFCb7aHh",
    title: "albany table",
    company: "marcos",
    image: "https://course-api.com/images/store/product-2.jpeg",
    price: 17999,
  },
  {
    id: "rec8kkCmSiMkbkiko",
    title: "accent chair",
    company: "caressa",
    image: "https://course-api.com/images/store/product-3.jpeg",
    price: 16599,
  },
  {
    id: "recBohCqQsot4Q4II",
    title: "wooden table",
    company: "caressa",
    image: "https://course-api.com/images/store/product-4.jpeg",

    price: 19599,
  },
  {
    id: "recDG1JRZnbpRHpoy",
    title: "dining table",
    company: "caressa",
    image: "https://course-api.com/images/store/product-5.jpeg",

    price: 16999,
  },
  {
    id: "recNWGyP7kjFhSqw3",
    title: "sofa set",
    company: "liddy",
    image: "https://course-api.com/images/store/product-6.jpeg",
    price: 14999,
  },
  {
    id: "recZEougL5bbY4AEx",
    title: "modern bookshelf",
    company: "marcos",
    image: "https://course-api.com/images/store/product-7.jpeg",
    price: 18999,
  },
  {
    id: "recjMK1jgTb2ld7sv",
    title: "emperor bed",
    company: "liddy",
    image: "https://course-api.com/images/store/product-8.jpeg",
    price: 21990,
  },
  {
    id: "recmg2a1ctaEJNZhu",
    title: "utopia sofa",
    company: "marcos",
    image: "https://course-api.com/images/store/product-9.jpeg",
    price: 27999,
  },
  {
    id: "recvKMNR3YFw0bEt3",
    title: "entertainment center",
    company: "liddy",
    image: "https://course-api.com/images/store/product-10.jpeg",
    price: 19999,
  },
  {
    id: "recxaXFy5IW539sgM",
    title: "albany sectional",
    company: "ikea",
    image: "https://course-api.com/images/store/product-11.jpeg",
    price: 21999,
  },
  {
    id: "recyqtRglGNGtO4Q5",
    title: "leather sofa",
    company: "liddy",
    image: "https://course-api.com/images/store/product-12.jpeg",
    price: 10999,
  },
];
